#! /bin/bash

echo ' '
read -p 'Would you like to clear the previous map database? (y/n): ' ansinput

if [ “$ansinput” = “y” ]
then
 printf '\n Map deleted \n'
 rm -f ~/.ros/rtabmap.db

elif [ “$ansinput” = “n” ]
then
 printf '\n Map kept \n'

else
 echo 'Warning: Not an acceptable option. Choose (y/n).
         '
fi

echo ' '

read -p 'Enter target world destination or d for default: ' input_choice

if [ “$input_choice” = “d” ]
then
  x-terminal-emulator -e roslaunch slam_project world.launch &

else
 x-terminal-emulator -e roslaunch slam_project world.launch world_file:=$input_choice &
fi

sleep 5 &&

x-terminal-emulator -e roslaunch slam_project teleop.launch &

sleep 5 &&

echo ' '
read -p 'Press any key to continue to mapping... ' -n1 -s

x-terminal-emulator -e roslaunch slam_project mapping.launch simulation:=true &
sleep 5 &&
x-terminal-emulator -e roslaunch slam_project rviz.launch

echo ' '
echo 'Script Completed'
echo ' '
